version: '3'

vars:
  BACKEND_DIR: ./backend
  FRONTEND_DIR: ./frontend

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  setup:
    desc: Install all dependencies
    cmds:
      - task: setup-backend
      - task: setup-frontend

  setup-backend:
    desc: Setup backend dependencies
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go mod tidy

  setup-frontend:
    desc: Setup frontend dependencies
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm install

  dev:
    desc: Start development environment
    cmds:
      - echo "Starting development servers..."

  build:
    desc: Build all
    cmds:
      - task: build-backend
      - task: build-frontend

  build-backend:
    desc: Build backend
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - go build -o bin/server cmd/server/main.go

  build-frontend:
    desc: Build frontend
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm run build